#!/usr/bin/env python3
"""Generates report_fmt.vh: the UART status line of ber_top (gs) as a char_at(idx) case table,
and is the single source of the field layout that tools/ber_parse.py decodes (TASK-5055).
Line: 'B' + for each field ' ' + hex(width/4 digits) + '\\r\\n'."""
import os
FIELDS = [  # name, bits  (order = order on the line)
    ('t25', 32), ('tcnt', 32), ('rcnt', 32), ('flg', 8), ('words', 48), ('errw', 32), ('errb', 32),
    ('code', 32), ('inj', 8), ('exec', 8), ('cmd', 8), ('cfg', 8),
    ('pwords', 48), ('perrw', 32), ('perrb', 32), ('pcode', 32), ('pflg', 8), ('pexec', 8),
    ('pcmd', 8), ('pinj', 8), ('pver', 8), ('pcfg', 8), ('pframes', 32),
]
REP_BITS = sum(b for _, b in FIELDS)


def line_chars():
    """list of ('c', char) | ('n', bit_lsb_of_nibble_in_rep)"""
    out = [('c', 'B')]
    pos = REP_BITS
    for _, bits in FIELDS:
        out.append(('c', ' '))
        for k in range(bits // 4):
            pos -= 4
            out.append(('n', pos))
    out += [('c', '\r'), ('c', '\n')]
    return out


def main():
    ch = line_chars()
    v = ['// generated by gen_report_fmt.py - do not edit', 'localparam REP_BITS = %d;' % REP_BITS,
         'localparam LINE_LEN = %d;' % len(ch), 'function [7:0] hexc(input [3:0] n);',
         '    hexc = (n < 10) ? (8\'h30 + n) : (8\'h57 + n);', 'endfunction',
         'function [7:0] char_at(input [7:0] i, input [REP_BITS-1:0] r);', '    case (i)']
    for i, (t, x) in enumerate(ch):
        v.append("        8'd%d: char_at = %s;" % (i, "8'h%02X" % ord(x) if t == 'c' else 'hexc(r[%d +: 4])' % x))
    v += ["        default: char_at = 8'h20;", '    endcase', 'endfunction', '']
    open(os.path.join(os.path.dirname(os.path.abspath(__file__)), 'report_fmt.vh'), 'w').write('\n'.join(v))
    print('REP_BITS=%d LINE_LEN=%d' % (REP_BITS, len(ch)))


if __name__ == '__main__':
    main()
